from config import MAIL_SERVER, MAIL_PORT, MAIL_USE_TLS, EMAIL_ID, EMAIL_PASSWORD


class EmailConfig:

    # Flask-Mail
    MAIL_SERVER = MAIL_SERVER
    MAIL_PORT = MAIL_PORT
    MAIL_USE_TLS = MAIL_USE_TLS
    EMAIL_ID = EMAIL_ID
    EMAIL_PASSWORD = EMAIL_PASSWORD
